cat("Welcome to the StabEco project.\n")
require(igraph)
require(deSolve)
require(rootSolve)
require(plyr)
require(reshape2)
require(ggplot2)
require(yuima)
require(xts)
require(TTR)
require(dplyr)
require(StabEco)