cat("Welcome to the StabEco project.\n")
require(StabEco) # This package has to be listed FIRST, otherwise it can't be loaded
require(ggplot2)
require(igraph)
#require(deSolve)
#require(rootSolve)
#require(plyr)
#require(reshape2)
require(yuima)
#require(xts)
#require(TTR)
#require(dplyr)
