library(R6)
library(igraph)
# library(bipartite) # use sortweb function

#' @title bipartite graph
#' @field type type of bipartite graph
#' \describe{
#' \item{bipartite_regular}{a regular bipartite graph, restriction: n1 = n2}
#' \item{bipartite_gnm}{a bipartite graph generated by ER model}
#' \item{bipartite_real}{a bipartite graph gotten from the incidency matrix of an empirical network}
#' }
#' @examples 
#' BiGraph$new(type = 'bipartite_regular', n1 = 50, k = 5)
BiGraph <- R6Class('BiGraph', 
  inherit = Graph,
  public = list(
    n1 = NULL, # node number in group 1
    n2 = NULL, # node number in group 2
    k = NULL, # average degree of nodes
    m = NULL, # number of (directed) edges
    # directed = NULL,
    #is_adj = NULL, # inner matrix is adjacency or incidency
    # set graph object from an incidency matrix
    set_graph_inc = function(graph_inc) {
      self$n1 = dim(graph_inc)[1]
      self$n2 = dim(graph_inc)[2]
      self$m = sum(graph_inc)
      self$k = 2 * self$m / (self$n1 + self$n2)
      self$n = self$n1 + self$n2
      private$G = graph_from_incidence_matrix(graph_inc)
      self$type = 'bipartite_real'
    },
    initialize = function(type = c('bipartite_regular', 'bipartite_gnm', 'bipartite_empty'), 
                          n1 = NULL, n2 = NULL, k = NULL, m = NULL, ...) {
      type <- match.arg(type)
      switch (type,
              bipartite_regular  = {
                G = sample_k_regular(n1, k, directed = TRUE)
                graph <- as.matrix(as_adjacency_matrix(G))
                private$G = graph_from_incidence_matrix(graph) # tricky!
                self$n1 <- n1
                self$n2 <- n1
                self$type <- type
                self$k <- k
                self$m <- self$k * (self$n1 + self$n2) / 2
                self$n <- self$n1 + self$n2
                # shuffle the rows and cols, to simulate a bipartite regular graph,
                # rather than a unipartite regular graph which have 0 value diagonal elements
                # this permutation does not change the eigenvalues
                # graph <- graph[sample.int(s[1]), sample.int(s[1])]
              },
              bipartite_gnm = {
                private$G = sample_bipartite(n1 = n1, n2 = n2, type = 'gnm', m = m) # m = k * (n1 + n2) / 2
                self$n1 <- n1
                self$n2 <- n2
                self$type <- type
                self$m <- m
                self$k <- round(2 * m / (n1 + n2))
                self$n <- self$n1 + self$n2
              },
              bipartite_empty = {
                # do nothing
                private$G = graph.empty()
              }
      )
    },
    get_graph = function(is_adj = TRUE) {
      if (is_adj == TRUE) {
        graph <- as.matrix(as_adjacency_matrix(private$G))
        return(graph)
      }
      else {
        graph <- as.matrix(as_incidence_matrix(private$G))
        return(graph)
      }
    },
    plot = function() {
      plot(private$G, layout = layout_as_bipartite,
           vertex.color = c("green", "cyan")[V(private$G)$type+1])
    }
  ))